Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name for the service.
  Name:
    Type: String
    Description: The name of the service.

Resources:
  LambdaExecutionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Sid: LambdaExecution
          Effect: Allow
          Action: lambda:InvokeFunction
          Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:http-test-function


Outputs:
  LambdaExecutionPolicyArn:
    Description: "The ARN of the ManagedPolicy to attatch to the task role."
    Value: !Ref LambdaExecutionPolicy
